In [1]:
import pandas as pd 
import numpy as np 

In [2]:
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA 
import pylab as pi 
from itertools import cycle

In [3]:
iris = load_iris()
num_samples, num_features = iris.data.shape

In [4]:
print(num_samples)

150


In [5]:
print(num_features)

4


In [6]:
print(list(iris.target_names))

['setosa', 'versicolor', 'virginica']


In [7]:
X = iris.data
pca = PCA(n_components=3, whiten = True).fit(X)

In [8]:
X_pca = pca.transform(X)

In [9]:
print(pca.components_)

[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]]


In [10]:
print(pca.explained_variance_ratio_)

[0.92461872 0.05306648 0.01710261]


In [11]:
print(sum(pca.explained_variance_ratio_))

0.9947878161267247
